# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DC Android
email: organizers@dcandroid.org
description: > # this means to ignore newlines until "baseurl:"
  DC Android (DCA) site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dcandroid.org" # the base hostname & protocol for your site
twitter_username: dcandroid
github_username:  dcandroid

# Build settings
markdown: kramdown
